language: python
sudo: true
dist: trusty
jobs:
  include:
  - python: "2.7"
    env: TEST_SUITE=ACL
  - python: "2.7"
    env: TEST_SUITE=OVC
  - python: "3.5"
    env: TEST_SUITE=PORTAL

install:
  - sudo apt install git

before_script: echo "before script for testsuite ${TEST_SUITE}"
script: echo  "execute test $TEST_SUITE"
after_script: echo "after script for testsuite ${TEST_SUITE}"
