language: python
sudo: true
dist: trusty
jobs:
  include:
  - python: "2.7"
  - python: "3.5"
install:
  - sudo apt install git

before_script: echo "before script for testsuite ${jobs}"
script: echo  "execute ${jobs}"
after_script: echo "after script for testsuite ${jobs}"
